name: generate-documentation

on: [push]

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: zhulik/redis-action@1.1.0
      with:
        redis version: "5"
        number of databases: 1
    - name: Set up as module
      run: |
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        npm install
        npm version patch
        mkdir /tmp/project
        cd /tmp/project
        npm init -y
        npm install faker ngrok puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/stripe-connect @userdashboard/storage-redis
        npm install -g mocha
        rm node_modules/@userdashboard/stripe-connect/*.js
        rm -rf node_modules/@userdashboard/stripe-connect/src
        rm -rf node_modules/@userdashboard/stripe-connect/languages
        cp /home/runner/work/stripe-connect/stripe-connect/*.js node_modules/@userdashboard/stripe-connect
        cp -R /home/runner/work/stripe-connect/stripe-connect/src/ node_modules/@userdashboard/stripe-connect/src/
        cp -R /home/runner/work/stripe-connect/stripe-connect/languages/ node_modules/@userdashboard/stripe-connect/languages/
        echo "global.applicationPath = __dirname" > main.js
        PACKAGE=`cat package.json`
        PACKAGE=${PACKAGE/\"description\"\: \"\"/\"dashboard\": \{ \"modules\"\: \[\"@userdashboard/stripe-connect\"\] \}}
        echo $PACKAGE > package.json
    - name: Generate documentation
      run: |
        mocha --grep returns --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/stripe-connect/**/*.test.js"
        mocha --grep screenshots --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/stripe-connect/**/*.test.js"
      working-directory: "/tmp/project"
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-redis"
        REDIS_URL: "redis://localhost:6379"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false   
        GENERATE_RESPONSE: true
        GENERATE_SCREENSHOTS: true
        RESPONSE_PATH: "/home/runner/work/stripe-connect/stripe-connect/documentation"
        SCREENSHOT_PATH: "/home/runner/work/stripe-connect/stripe-connect/documentation/screenshots"
        SCREENSHOT_LANGUAGES: "en,es,af,bg,pl,tr,hu,vi"
        LOG_LEVEL: "info,error,warn,log"
        STRIPE_KEY: ${{ secrets.STRIPE_KEY_8 }}
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY_8 }}
        STRIPE_JS: false
        CONNECT_WEBHOOK_ENDPOINT_SECRET: "replaced-at-runtime"
        NGROK: true
        TEST_SUITE_REUSABLE_WEBHOOK: true
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        external_repository: "userdashboard/userdashboard.github.io"
        personal_token: ${{ secrets.DOCUMENTATION_PAT }}
        publish_dir: documentation
        publish_branch: master
        keep_files: true
