name: test-postgresql

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup dependencies
      run: npm install mocha ngrok puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/storage-postgresql --no-save
    - name: Test unencrypted PostgreSQL storage
      run: npm test
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE_ENGINE: "@userdashboard/storage-postgresql"
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        STRIPE_KEY: ${{ secrets.STRIPE_KEY_6 }}
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY_6 }}
        STRIPE_JS: false
        CONNECT_WEBHOOK_ENDPOINT_SECRET: "replaced-at-runtime"
        NGROK: true
    - name: Test encrypted PostgreSQL storage
      run: npm test
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE_ENGINE: "@userdashboard/storage-postgresql"
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        STRIPE_KEY: ${{ secrets.STRIPE_KEY_6 }}
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY_6 }}
        STRIPE_JS: false
        CONNECT_WEBHOOK_ENDPOINT_SECRET: "replaced-at-runtime"
        NGROK: true
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"