name: test-fs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install mocha ngrok faker puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/storage-redis --no-save
    - name: Test encrypted file-system storage
      run: npm test
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        STRIPE_KEY: ${{ secrets.STRIPE_KEY_2 }}
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY_2 }}
        STRIPE_JS: false
        TEST_SUITE_REUSABLE_WEBHOOK: true
        CONNECT_WEBHOOK_ENDPOINT_SECRET: "replaced-at-runtime"
        NGROK: true
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"